dubbo:
  application:
    name: dubbo-boot-provider
  registry:
    protocol: zookeeper
    address: mse-ecd283d1-p.zk.mse.aliyuncs.com:2181
  protocol:
    name: dubbo
    port: -1
  metadata-report:
    address: zookeeper://mse-ecd283d1-p.zk.mse.aliyuncs.com:2181
server:
  port: 8889
